# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [42]:
import numpy as np
arr = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [58]:
arr1 =np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2 =np.ones((2,5))
arr2 = arr2.astype("int")
arr3 = np.vstack([arr1,arr2])
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [60]:
arr1 =np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2 =np.ones((2,5))
arr2 = arr2.astype("int")
arr3 = np.hstack([arr1,arr2])
arr3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [68]:
ar = np.array([[0,1,2,3,4],[5,6,7,8,9]])
ar.reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [76]:
ax=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])
ax.reshape(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [106]:
az = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
az.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [113]:
n =np.full((5,5),5)
np.square(n)

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [117]:
m = np.full((5,6),2)
m.mean()

2.0

## Question:9

### Find the standard deviation of the previous array in Q8?

In [119]:
np.std(m)

0.0

## Question:10

### Find the median of the previous array in Q8?

In [121]:
np.median(m)

2.0

## Question:11

### Find the transpose of the previous array in Q8?

In [122]:
np.transpose(m)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [134]:
an =np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print('\n',an)
an.trace() # easy way
ab = np.diagonal(an)
print(sum(ab)) # easy way too


 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
34


## Question:13

### Find the determinant of the previous array in Q12?

In [135]:
np.linalg.det(an)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [137]:
np.percentile(5,95)

5.0

## Question:15

### How to find if a given array has any null values?

In [152]:
array = np.array([0,0,1,2,3,4])
np.all(np.isnan(array))

False